// GENERATED by site/scripts/sync-seat-prices.mjs from src/config/pricing-2026-09-27.json — do not edit.
// Team seat list prices (USD per seat per month). seatPrices.test.js pins this to the sheet.
export const SEAT_PRICES = {
  sheet: 'pricing-2026-09-27.json',
  team_premium: {
    price_monthly: 125,
    price_monthly_annual_billing: 100
  },
  team_standard: {
    price_monthly: 25,
    price_monthly_annual_billing: 20
  }
} as const;
